---
title: "analyseBackground"
author: "Emily Williams"
date: "12/19/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
testbaseline <- read_csv("~/PycharmProjects/spireAudits/testbaseline.csv")

```

```{r,echo=F}
plot(testbaseline$baseRval)
plot(testbaseline$CH4 -testbaseline$medCH4*1.1,ylab='CH4 (ppm) above threshold',ylim=c(-.1,2.6))
plot(testbaseline$medC2H6)


```

```{r,echo=F}
testbaseline %>% 
  ggplot(aes(x=LONG,y=LAT,col=baseRval))+geom_point()


smalltest <- testbaseline %>% 
  filter(baseRval>.55)

write_csv(smalltest,'smallRvaltest.csv')
```


```{r cars}
testbaseline %>% 
  filter(CH4 > medCH4) %>% 
  ggplot(aes(x=LONG,y=LAT,col=CH4-medCH4))+geom_point()

testbaseline %>% 
  ggplot(aes(x=LONG,y=LAT,col=medC2H6))+geom_point()


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
